export const mockList = [
  {
    strMealThumb:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQNfQEYRdF4g63WJMy4K6dpmaIzkIZw1Tk2jJy5_K01sAWS6NSf3XvkEt-__p8x7rLYTG2lX6oiQT6ZIv8",
    strIngredient1: "csdsc",
    strIngredient13: "cscsdcdsc",
    strIngredient14: "cscsdcdsc",
    strIngredient15: "dcdsc",
    strIngredient16: "csdsc",
    strIngredient17: "csdsc",
    strIngredient167: "cscdsc",
    strIngredient168: "cscsdcdsc",
    strMeal: "borshh",
    strCategory: "beef",
  },
  {
    strMealThumb:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQNfQEYRdF4g63WJMy4K6dpmaIzkIZw1Tk2jJy5_K01sAWS6NSf3XvkEt-__p8x7rLYTG2lX6oiQT6ZIv8",
    strIngredient1: "csdsc",
    strIngredient13: "cscsdcdsc",
    strIngredient14: "cscsdcdsc",
    strIngredient15: "dcdsc",
    strIngredient16: "csdsc",
    strIngredient17: "csdsc",
    strIngredient167: "cscdsc",
    strIngredient168: "cscsdcdsc",
    strMeal: "borshh",
    strCategory: "beef",
  },
  {
    strMealThumb:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQNfQEYRdF4g63WJMy4K6dpmaIzkIZw1Tk2jJy5_K01sAWS6NSf3XvkEt-__p8x7rLYTG2lX6oiQT6ZIv8",
    strIngredient1: "csdsc",
    strIngredient13: "cscsdcdsc",
    strIngredient14: "cscsdcdsc",
    strIngredient15: "dcdsc",
    strIngredient16: "csdsc",
    strIngredient17: "csdsc",
    strIngredient167: "cscdsc",
    strIngredient168: "cscsdcdsc",
    strMeal: "borshh",
    strCategory: "beef",
  },
  {
    strMealThumb:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQNfQEYRdF4g63WJMy4K6dpmaIzkIZw1Tk2jJy5_K01sAWS6NSf3XvkEt-__p8x7rLYTG2lX6oiQT6ZIv8",
    strIngredient1: "csdsc",
    strIngredient13: "cscsdcdsc",
    strIngredient14: "cscsdcdsc",
    strIngredient15: "dcdsc",
    strIngredient16: "csdsc",
    strIngredient17: "csdsc",
    strIngredient167: "cscdsc",
    strIngredient168: "cscsdcdsc",
    strMeal: "borshh",
    strCategory: "beef",
  },
  {
    strMealThumb:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQNfQEYRdF4g63WJMy4K6dpmaIzkIZw1Tk2jJy5_K01sAWS6NSf3XvkEt-__p8x7rLYTG2lX6oiQT6ZIv8",
    strIngredient1: "csdsc",
    strIngredient13: "cscsdcdsc",
    strIngredient14: "cscsdcdsc",
    strIngredient15: "dcdsc",
    strIngredient16: "csdsc",
    strIngredient17: "csdsc",
    strIngredient167: "cscdsc",
    strIngredient168: "cscsdcdsc",
    strMeal: "borshh",
    strCategory: "beef",
  },
  {
    strMealThumb:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQNfQEYRdF4g63WJMy4K6dpmaIzkIZw1Tk2jJy5_K01sAWS6NSf3XvkEt-__p8x7rLYTG2lX6oiQT6ZIv8",
    strIngredient1: "csdsc",
    strIngredient13: "cscsdcdsc",
    strIngredient14: "cscsdcdsc",
    strIngredient15: "dcdsc",
    strIngredient16: "csdsc",
    strIngredient17: "csdsc",
    strIngredient167: "cscdsc",
    strIngredient168: "cscsdcdsc",
    strMeal: "borshh",
    strCategory: "beef",
  },
  {
    strMealThumb:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQNfQEYRdF4g63WJMy4K6dpmaIzkIZw1Tk2jJy5_K01sAWS6NSf3XvkEt-__p8x7rLYTG2lX6oiQT6ZIv8",
    strIngredient1: "csdsc",
    strIngredient13: "cscsdcdsc",
    strIngredient14: "cscsdcdsc",
    strIngredient15: "dcdsc",
    strIngredient16: "csdsc",
    strIngredient17: "csdsc",
    strIngredient167: "cscdsc",
    strIngredient168: "cscsdcdsc",
    strMeal: "borshh",
    strCategory: "beef",
  },
  {
    strMealThumb:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQNfQEYRdF4g63WJMy4K6dpmaIzkIZw1Tk2jJy5_K01sAWS6NSf3XvkEt-__p8x7rLYTG2lX6oiQT6ZIv8",
    strIngredient1: "csdsc",
    strIngredient13: "cscsdcdsc",
    strIngredient14: "cscsdcdsc",
    strIngredient15: "dcdsc",
    strIngredient16: "csdsc",
    strIngredient17: "csdsc",
    strIngredient167: "cscdsc",
    strIngredient168: "cscsdcdsc",
    strMeal: "borshh",
    strCategory: "beef",
  },
  {
    strMealThumb:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQNfQEYRdF4g63WJMy4K6dpmaIzkIZw1Tk2jJy5_K01sAWS6NSf3XvkEt-__p8x7rLYTG2lX6oiQT6ZIv8",
    strIngredient1: "csdsc",
    strIngredient13: "cscsdcdsc",
    strIngredient14: "cscsdcdsc",
    strIngredient15: "dcdsc",
    strIngredient16: "csdsc",
    strIngredient17: "csdsc",
    strIngredient167: "cscdsc",
    strIngredient168: "cscsdcdsc",
    strMeal: "borshh",
    strCategory: "beef",
  },
  {
    strMealThumb:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQNfQEYRdF4g63WJMy4K6dpmaIzkIZw1Tk2jJy5_K01sAWS6NSf3XvkEt-__p8x7rLYTG2lX6oiQT6ZIv8",
    strIngredient1: "csdsc",
    strIngredient13: "cscsdcdsc",
    strIngredient14: "cscsdcdsc",
    strIngredient15: "dcdsc",
    strIngredient16: "csdsc",
    strIngredient17: "csdsc",
    strIngredient167: "cscdsc",
    strIngredient168: "cscsdcdsc",
    strMeal: "borshh",
    strCategory: "beef",
  },
  {
    strMealThumb:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQNfQEYRdF4g63WJMy4K6dpmaIzkIZw1Tk2jJy5_K01sAWS6NSf3XvkEt-__p8x7rLYTG2lX6oiQT6ZIv8",
    strIngredient1: "csdsc",
    strIngredient13: "cscsdcdsc",
    strIngredient14: "cscsdcdsc",
    strIngredient15: "dcdsc",
    strIngredient16: "csdsc",
    strIngredient17: "csdsc",
    strIngredient167: "cscdsc",
    strIngredient168: "cscsdcdsc",
    strMeal: "borshh",
    strCategory: "beef",
  },
];
